services:
  postgres:
    container_name: "snaily-cad-postgres"
    image: postgres
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN_URL: ${CORS_ORIGIN_URL}
      NEXT_PUBLIC_PROD_ORIGIN: ${NEXT_PUBLIC_PROD_ORIGIN}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./.dev-data:/var/lib/postgresql/data
